import { test } from '@playwright/test';
import { loginAsAdmin, visitPackageRoute } from './helpers/package-docs.js';
import { timetableRoutes } from './helpers/timetable-routes.js';

const packageSuites = [
  {
    name: 'CorePackage',
    routes: [
      { title: 'Dashboard', path: '/dashboard', expect: /Dashboard|School/i },
    ],
  },
  {
    name: 'Installer',
    routes: [
      { title: 'Installer', path: '/install', expect: /Install|Installer|School/i },
    ],
  },
  {
    name: 'BundleInstaller',
    routes: [
      { title: 'Bundle Installer', path: '/bundle-installer', expect: /Bundle|Installer|Upload/i },
    ],
  },
  {
    name: 'ContactBundle',
    routes: [
      { title: 'Contact', path: '/contact', expect: /Contact|Inquiry|Inquiries/i },
    ],
  },
  {
    name: 'DataTransfer',
    routes: [
      { title: 'Data Transfer', path: '/data-transfer', expect: /Import|Export|Transfer/i },
    ],
  },
  {
    name: 'StudentManagement',
    routes: [
      { title: 'Students', path: '/students' },
      { title: 'Create Student', path: '/students/create', expect: /Create|Student/i },
      { title: 'Student Profile', path: '/students/1', expect: /Student|Profile|Parent/i },
      { title: 'Edit Student', path: '/students/1/edit', expect: /Edit|Student/i },
      { title: 'Student Health Records', path: '/students/1/health', expect: /Health|Student/i },
      { title: 'Student Documents', path: '/students/1/documents', expect: /Documents|Student/i },
      { title: 'Student Activity Logs', path: '/students/1/activities', expect: /Activity|Student/i },
      { title: 'Student Contacts', path: '/students/1/contacts', expect: /Contacts|Student/i },
    ],
  },
  {
    name: 'StaffManagement',
    routes: [
      { title: 'Staff', path: '/staff' },
      { title: 'Create Staff', path: '/staff/create', expect: /Create|Staff/i },
      { title: 'Staff Profile', path: '/staff/1', expect: /Staff|Profile|Department/i },
      { title: 'Edit Staff', path: '/staff/1/edit', expect: /Edit|Staff/i },
    ],
  },
  {
    name: 'ClassManagement',
    routes: [
      { title: 'Academic Years', path: '/academic-years' },
      { title: 'Create Academic Year', path: '/academic-years/create', expect: /Create|Academic Year/i },
      { title: 'Academic Year Details', path: '/academic-years/1', expect: /Academic Year|2024/i },
      { title: 'Edit Academic Year', path: '/academic-years/1/edit', expect: /Edit|Academic Year/i },
      { title: 'Classes', path: '/classes' },
      { title: 'Create Class', path: '/classes/create', expect: /Create|Class/i },
      { title: 'Class Details', path: '/classes/1', expect: /Class|Section|Batch/i },
      { title: 'Edit Class', path: '/classes/1/edit', expect: /Edit|Class/i },
      { title: 'Sections', path: '/sections' },
      { title: 'Create Section', path: '/sections/create', expect: /Create|Section/i },
      { title: 'Section Details', path: '/sections/1', expect: /Section|Class/i },
      { title: 'Edit Section', path: '/sections/1/edit', expect: /Edit|Section/i },
      { title: 'Batches', path: '/batches' },
      { title: 'Create Batch', path: '/batches/create', expect: /Create|Batch/i },
      { title: 'Batch Details', path: '/batches/1', expect: /Batch|Class|Section/i },
      { title: 'Edit Batch', path: '/batches/1/edit', expect: /Edit|Batch/i },
    ],
  },
  {
    name: 'SubjectManagement',
    routes: [
      { title: 'Subjects', path: '/subjects' },
      { title: 'Create Subject', path: '/subjects/create', expect: /Create|Subject/i },
      { title: 'Subject Details', path: '/subjects/1', expect: /Subject|Mathematics/i },
      { title: 'Edit Subject', path: '/subjects/1/edit', expect: /Edit|Subject/i },
      { title: 'Class-Subjects', path: '/class-subjects' },
      { title: 'Create Class Subject', path: '/class-subjects/create', expect: /Create|Class|Subject/i },
      { title: 'Class Subject Details', path: '/class-subjects/1', expect: /Class|Subject/i },
      { title: 'Edit Class Subject', path: '/class-subjects/1/edit', expect: /Edit|Class|Subject/i },
      { title: 'Curriculum', path: '/curriculums' },
      { title: 'Create Curriculum', path: '/curriculums/create', expect: /Create|Curriculum/i },
      { title: 'Curriculum Details', path: '/curriculums/1', expect: /Curriculum|Subject/i },
      { title: 'Edit Curriculum', path: '/curriculums/1/edit', expect: /Edit|Curriculum/i },
      { title: 'Lesson Plans', path: '/lesson-plans' },
      { title: 'Create Lesson Plan', path: '/lesson-plans/create', expect: /Create|Lesson Plan/i },
      { title: 'Lesson Plan Details', path: '/lesson-plans/1', expect: /Lesson Plan|Unit/i },
      { title: 'Edit Lesson Plan', path: '/lesson-plans/1/edit', expect: /Edit|Lesson Plan/i },
      { title: 'Textbooks', path: '/textbooks' },
      { title: 'Create Textbook', path: '/textbooks/create', expect: /Create|Textbook/i },
      { title: 'Textbook Details', path: '/textbooks/1', expect: /Textbook|Mathematics/i },
      { title: 'Edit Textbook', path: '/textbooks/1/edit', expect: /Edit|Textbook/i },
      { title: 'Teacher Assignments', path: '/teacher-subject-mappings' },
      { title: 'Create Teacher Assignment', path: '/teacher-subject-mappings/create', expect: /Create|Teacher|Assignment/i },
      { title: 'Teacher Assignment Details', path: '/teacher-subject-mappings/1', expect: /Teacher|Subject|Class/i },
      { title: 'Edit Teacher Assignment', path: '/teacher-subject-mappings/1/edit', expect: /Edit|Teacher|Assignment/i },
    ],
  },
  {
    name: 'AttendanceManagement',
    routes: [
      { title: 'Attendance Overview', path: '/attendance-overview', expect: /Attendance Overview|Students Today|Teachers Today/i },
      { title: 'Student Attendance', path: '/studentAttendance' },
      { title: 'Create Student Attendance', path: '/studentAttendance/create', expect: /Create|Mark|Student Attendance/i },
      { title: 'Student Attendance Details', path: '/studentAttendance/1', expect: /Attendance|Record|Student/i },
      { title: 'Edit Student Attendance', path: '/studentAttendance/1/edit', expect: /Edit|Student Attendance/i },
      { title: 'Teacher Attendance', path: '/teacherAttendance' },
      { title: 'Create Teacher Attendance', path: '/teacherAttendance/create', expect: /Create|Mark|Teacher Attendance/i },
      { title: 'Teacher Attendance Details', path: '/teacherAttendance/1', expect: /Attendance|Record|Teacher/i },
      { title: 'Edit Teacher Attendance', path: '/teacherAttendance/1/edit', expect: /Edit|Teacher Attendance/i },
      { title: 'Student Leave Requests', path: '/studentLeaveRequest' },
      { title: 'Create Student Leave Request', path: '/studentLeaveRequest/create', expect: /Create|Submit|Leave Request/i },
      { title: 'Student Leave Request Details', path: '/studentLeaveRequest/1', expect: /Leave Request|Student/i },
      { title: 'Edit Student Leave Request', path: '/studentLeaveRequest/1/edit', expect: /Edit|Leave Request/i },
      { title: 'Teacher Leave Requests', path: '/teacherLeaveRequest' },
      { title: 'Create Teacher Leave Request', path: '/teacherLeaveRequest/create', expect: /Create|Submit|Leave Request/i },
      { title: 'Teacher Leave Request Details', path: '/teacherLeaveRequest/1', expect: /Leave Request|Teacher/i },
      { title: 'Edit Teacher Leave Request', path: '/teacherLeaveRequest/1/edit', expect: /Edit|Leave Request/i },
      { title: 'Holidays', path: '/holiday' },
      { title: 'Create Holiday', path: '/holiday/create', expect: /Create|Add|Holiday/i },
      { title: 'Holiday Details', path: '/holiday/1', expect: /Holiday|Independence/i },
      { title: 'Edit Holiday', path: '/holiday/1/edit', expect: /Edit|Holiday/i },
    ],
  },
  {
    name: 'TimetableManagement',
    routes: timetableRoutes,
  },
  {
    name: 'RbacManagement',
    routes: [
      { title: 'Roles', path: '/roles' },
      { title: 'Create Role', path: '/roles/create', expect: /Create|Role/i },
      { title: 'Role Details', path: '/roles/1', expect: /Role|Permission/i },
      { title: 'Edit Role', path: '/roles/1/edit', expect: /Edit|Role/i },
      { title: 'Permissions', path: '/permissions' },
      { title: 'Create Permission', path: '/permissions/create', expect: /Create|Permission/i },
      { title: 'Permission Details', path: '/permissions/1', expect: /Permission|Role/i },
      { title: 'Edit Permission', path: '/permissions/1/edit', expect: /Edit|Permission/i },
      { title: 'Role Permissions', path: '/role-permissions' },
      { title: 'Edit Role Permissions', path: '/role-permissions/1/edit', expect: /Role|Permissions/i },
      { title: 'User Roles', path: '/user-roles' },
      { title: 'Edit User Roles', path: '/user-roles/1/edit', expect: /User|Roles/i },
      { title: 'Edit User Permissions', path: '/user-permissions/1/edit', expect: /User|Permissions/i },
      { title: 'Create User', path: '/users/create', expect: /Create|User/i },
    ],
  },
  {
    name: 'ExamManagement',
    routes: [
      { title: 'Exams', path: '/exam' },
      { title: 'Create Exam', path: '/exam/create', expect: /Create|Exam/i },
      { title: 'Exam Details', path: '/exam/1', expect: /Exam|Mid-Term/i },
      { title: 'Edit Exam', path: '/exam/1/edit', expect: /Edit|Exam/i },
      { title: 'Exam Schedules', path: '/examSchedule' },
      { title: 'Create Exam Schedule', path: '/examSchedule/create', expect: /Create|Exam Schedule/i },
      { title: 'Exam Schedule Details', path: '/examSchedule/1', expect: /Exam Schedule|Subject/i },
      { title: 'Edit Exam Schedule', path: '/examSchedule/1/edit', expect: /Edit|Exam Schedule/i },
      { title: 'Grading Schemes', path: '/gradingScheme' },
      { title: 'Create Grading Scheme', path: '/gradingScheme/create', expect: /Create|Grading Scheme/i },
      { title: 'Grading Scheme Details', path: '/gradingScheme/1', expect: /Grading Scheme|A\+/i },
      { title: 'Edit Grading Scheme', path: '/gradingScheme/1/edit', expect: /Edit|Grading Scheme/i },
      { title: 'Student Marks', path: '/studentMark' },
      { title: 'Create Student Mark', path: '/studentMark/create', expect: /Create|Student Mark/i },
      { title: 'Student Mark Details', path: '/studentMark/1', expect: /Student Mark|Marks/i },
      { title: 'Edit Student Mark', path: '/studentMark/1/edit', expect: /Edit|Student Mark/i },
      { title: 'Student Report Cards', path: '/studentReportCard' },
      { title: 'Create Student Report Card', path: '/studentReportCard/create', expect: /Create|Report Card/i },
      { title: 'Student Report Card Details', path: '/studentReportCard/1', expect: /Report Card|Student/i },
      { title: 'Edit Student Report Card', path: '/studentReportCard/1/edit', expect: /Edit|Report Card/i },
    ],
  },
  {
    name: 'FeeManagement',
    routes: [
      { title: 'Fee Categories', path: '/feeCategory' },
      { title: 'Create Fee Category', path: '/feeCategory/create', expect: /Create|Fee Category/i },
      { title: 'Fee Category Details', path: '/feeCategory/1', expect: /Fee Category|Tuition/i },
      { title: 'Edit Fee Category', path: '/feeCategory/1/edit', expect: /Edit|Fee Category/i },
      { title: 'Fee Structures', path: '/feeStructure' },
      { title: 'Create Fee Structure', path: '/feeStructure/create', expect: /Create|Fee Structure/i },
      { title: 'Fee Structure Details', path: '/feeStructure/1', expect: /Fee Structure|Amount/i },
      { title: 'Edit Fee Structure', path: '/feeStructure/1/edit', expect: /Edit|Fee Structure/i },
      { title: 'Student Fees', path: '/studentFee' },
      { title: 'Create Student Fee', path: '/studentFee/create', expect: /Create|Student Fee/i },
      { title: 'Student Fee Details', path: '/studentFee/1', expect: /Student Fee|Amount/i },
      { title: 'Edit Student Fee', path: '/studentFee/1/edit', expect: /Edit|Student Fee/i },
      { title: 'Payments', path: '/feePayment' },
      { title: 'Create Payment', path: '/feePayment/create', expect: /Create|Payment/i },
      { title: 'Payment Details', path: '/feePayment/1', expect: /Payment|Amount/i },
      { title: 'Edit Payment', path: '/feePayment/1/edit', expect: /Edit|Payment/i },
      { title: 'Discounts', path: '/discount' },
      { title: 'Create Discount', path: '/discount/create', expect: /Create|Discount/i },
      { title: 'Discount Details', path: '/discount/1', expect: /Discount|Type/i },
      { title: 'Edit Discount', path: '/discount/1/edit', expect: /Edit|Discount/i },
      { title: 'Student Discounts', path: '/studentDiscount' },
      { title: 'Create Student Discount', path: '/studentDiscount/create', expect: /Create|Student Discount/i },
      { title: 'Student Discount Details', path: '/studentDiscount/1', expect: /Student Discount|Discount/i },
      { title: 'Edit Student Discount', path: '/studentDiscount/1/edit', expect: /Edit|Student Discount/i },
      { title: 'Expenses', path: '/expense' },
      { title: 'Create Expense', path: '/expense/create', expect: /Create|Expense/i },
      { title: 'Expense Details', path: '/expense/1', expect: /Expense|Amount/i },
      { title: 'Edit Expense', path: '/expense/1/edit', expect: /Edit|Expense/i },
      { title: 'Financial Reports', path: '/financialReport' },
      { title: 'Create Financial Report', path: '/financialReport/create', expect: /Create|Financial Report/i },
      { title: 'Financial Report Details', path: '/financialReport/1', expect: /Financial Report|Report/i },
      { title: 'Edit Financial Report', path: '/financialReport/1/edit', expect: /Edit|Financial Report/i },
    ],
  },
  {
    name: 'CommunicationManagement',
    routes: [
      { title: 'Messages', path: '/message' },
      { title: 'Create Message', path: '/message/create', expect: /Create|Message/i },
      { title: 'Message Details', path: '/message/1', expect: /Message|Welcome/i },
      { title: 'Edit Message', path: '/message/1/edit', expect: /Edit|Message/i },
      { title: 'Recipients', path: '/messageRecipient' },
      { title: 'Create Recipient', path: '/messageRecipient/create', expect: /Create|Recipient/i },
      { title: 'Recipient Details', path: '/messageRecipient/1', expect: /Recipient|Message/i },
      { title: 'Edit Recipient', path: '/messageRecipient/1/edit', expect: /Edit|Recipient/i },
      { title: 'Circulars', path: '/circular' },
      { title: 'Create Circular', path: '/circular/create', expect: /Create|Circular/i },
      { title: 'Circular Details', path: '/circular/1', expect: /Circular|Prize/i },
      { title: 'Edit Circular', path: '/circular/1/edit', expect: /Edit|Circular/i },
      { title: 'Notification Prefs', path: '/notificationSetting' },
      { title: 'Create Notification Setting', path: '/notificationSetting/create', expect: /Create|Notification/i },
      { title: 'Notification Setting Details', path: '/notificationSetting/1', expect: /Notification|Setting/i },
      { title: 'Edit Notification Setting', path: '/notificationSetting/1/edit', expect: /Edit|Notification/i },
    ],
  },
  {
    name: 'HostelTransportManagement',
    routes: [
      { title: 'Hostels', path: '/hostels' },
      { title: 'Create Hostel', path: '/hostels/create', expect: /Create|Hostel/i },
      { title: 'Hostel Details', path: '/hostels/1', expect: /Hostel|Rooms/i },
      { title: 'Edit Hostel', path: '/hostels/1/edit', expect: /Edit|Hostel/i },
      { title: 'Hostel Rooms', path: '/hostel-rooms' },
      { title: 'Create Hostel Room', path: '/hostel-rooms/create', expect: /Create|Hostel Room|Room/i },
      { title: 'Hostel Room Details', path: '/hostel-rooms/1', expect: /Room|Hostel|Capacity/i },
      { title: 'Edit Hostel Room', path: '/hostel-rooms/1/edit', expect: /Edit|Room/i },
      { title: 'Student Hostels', path: '/student-hostels' },
      { title: 'Create Student Hostel', path: '/student-hostels/create', expect: /Create|Student Hostel/i },
      { title: 'Student Hostel Details', path: '/student-hostels/1', expect: /Student Hostel|Student|Room/i },
      { title: 'Edit Student Hostel', path: '/student-hostels/1/edit', expect: /Edit|Student Hostel/i },
      { title: 'Facilities', path: '/facilities' },
      { title: 'Create Facility', path: '/facilities/create', expect: /Create|Facility/i },
      { title: 'Facility Details', path: '/facilities/1', expect: /Facility|Hostel/i },
      { title: 'Edit Facility', path: '/facilities/1/edit', expect: /Edit|Facility/i },
      { title: 'Facility Bookings', path: '/facility-bookings' },
      { title: 'Create Facility Booking', path: '/facility-bookings/create', expect: /Create|Facility Booking/i },
      { title: 'Facility Booking Details', path: '/facility-bookings/1', expect: /Facility Booking|Booking/i },
      { title: 'Edit Facility Booking', path: '/facility-bookings/1/edit', expect: /Edit|Facility Booking/i },
      { title: 'Transportation', path: '/transportation' },
      { title: 'Create Transportation', path: '/transportation/create', expect: /Create|Transportation/i },
      { title: 'Transportation Details', path: '/transportation/1', expect: /Transportation|Route|Vehicle/i },
      { title: 'Edit Transportation', path: '/transportation/1/edit', expect: /Edit|Transportation/i },
      { title: 'Student Transport', path: '/student-transport' },
      { title: 'Create Student Transport', path: '/student-transport/create', expect: /Create|Student Transport/i },
      { title: 'Student Transport Details', path: '/student-transport/1', expect: /Student Transport|Student|Route/i },
      { title: 'Edit Student Transport', path: '/student-transport/1/edit', expect: /Edit|Student Transport/i },
    ],
  },
];

test.describe.configure({ mode: 'serial' });

for (const suite of packageSuites) {
  test(`${suite.name} bundle routes`, async ({ page }) => {
    test.setTimeout(120_000);

    await page.setViewportSize({ width: 1440, height: 900 });
    await loginAsAdmin(page);

    for (const route of suite.routes) {
      await visitPackageRoute(page, route);
    }
  });
}
