export const timetableRoutes = [
  { title: 'Timetable', path: '/timetable', expect: /Timetable|Period \/ Day|Select a class/i },
  { title: 'Filtered Timetable', path: '/timetable?class_id=1&section_id=1&academic_year_id=1', expect: /Timetable|Mathematics|English|Science/i },
  { title: 'Create Timetable Entry', path: '/timetable/create', expect: /Create|Add Timetable|Timetable Entry/i },
  { title: 'Timetable Entry Details', path: '/timetable/1', expect: /Timetable|Entry|Class/i },
  { title: 'Edit Timetable Entry', path: '/timetable/1/edit', expect: /Edit|Timetable/i },
  { title: 'Rooms', path: '/room' },
  { title: 'Create Room', path: '/room/create', expect: /Create|Add Room|Room/i },
  { title: 'Room Details', path: '/room/1', expect: /Room 101|Capacity|Timetable/i },
  { title: 'Edit Room', path: '/room/1/edit', expect: /Edit|Room/i },
  { title: 'Periods', path: '/period' },
  { title: 'Create Period', path: '/period/create', expect: /Create|Add Period|Period/i },
  { title: 'Period Details', path: '/period/1', expect: /Period|08:00|08:45/i },
  { title: 'Edit Period', path: '/period/1/edit', expect: /Edit|Period/i },
  { title: 'Days', path: '/day' },
  { title: 'Create Day', path: '/day/create', expect: /Create|Add Day|Day/i },
  { title: 'Day Details', path: '/day/1', expect: /Day|Monday|Timetable/i },
  { title: 'Edit Day', path: '/day/1/edit', expect: /Edit|Day/i },
  { title: 'Substitutions', path: '/substituteAssignment', expect: /Substitutions|Substitute/i },
  { title: 'Create Substitute Assignment', path: '/substituteAssignment/create', expect: /Create|Add Substitute|Substitute/i },
  { title: 'Substitute Assignment Details', path: '/substituteAssignment/1', expect: /Substitute|Assignment|Teacher/i },
  { title: 'Edit Substitute Assignment', path: '/substituteAssignment/1/edit', expect: /Edit|Substitute/i },
  { title: 'Special Events', path: '/specialEvent' },
  { title: 'Create Special Event', path: '/specialEvent/create', expect: /Create|Add Event|Special Event/i },
  { title: 'Special Event Details', path: '/specialEvent/1', expect: /Special Event|Annual Sports/i },
  { title: 'Edit Special Event', path: '/specialEvent/1/edit', expect: /Edit|Special Event/i },
];
